import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { Layout, Navbar, Sidebar } from "~/component/Component";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
      <h1>Hello world</h1>
    </>
  );
}
